/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Entidades.SolicitudALobby;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import logica.ControladorVentanas;
import mensajes.Mensaje;

/**
 *
 * @author Gabriel
 */
public class vistaRegistro extends javax.swing.JFrame implements Observer{
    ControladorVentanas controlador;
    /**
     * Creates new form vistaRegistro
     */
    public vistaRegistro(ControladorVentanas controlador) {
        this.controlador=controlador;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtPartida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUnirse = new javax.swing.JButton();
        btnValidar = new javax.swing.JButton();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(240, 202, 148));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        txtNombre.setHighlighter(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 20));

        txtPartida.setBackground(new java.awt.Color(240, 202, 148));
        txtPartida.setForeground(new java.awt.Color(0, 0, 0));
        txtPartida.setBorder(null);
        txtPartida.setHighlighter(null);
        txtPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUnirse.setBorderPainted(false);
        btnUnirse.setContentAreaFilled(false);
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 150, 50));

        btnValidar.setBorderPainted(false);
        btnValidar.setContentAreaFilled(false);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 330, 40));

        btnVolverInicio.setText("jButton1");
        btnVolverInicio.setBorderPainted(false);
        btnVolverInicio.setContentAreaFilled(false);
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 140, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        SolicitudALobby solicitud=new SolicitudALobby(txtNombre.getText(), txtPartida.getText());
        controlador.registrarUsuarioEnLobby(solicitud);
    }//GEN-LAST:event_btnUnirseActionPerformed

    private void txtPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if (!txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre Correcto", "Notificacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Poner Datos Correctos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        vistaInicio inicio = new vistaInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnirse;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPartida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Mensaje mensaje=(Mensaje)arg;
        if(mensaje.getTipo().equalsIgnoreCase("UsuarioValido")){
            controlador.cambiaraVentanaLobby(this);
        }else if(mensaje.getTipo().equalsIgnoreCase("UsuarioInvalido")){
            JOptionPane.showMessageDialog(this, (String)mensaje.getContenido(), "Error", JOptionPane.WARNING_MESSAGE);
        }else if(mensaje.getTipo().equalsIgnoreCase("LobbyInexistente")){
            JOptionPane.showMessageDialog(this, (String)mensaje.getContenido(), "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, (String)mensaje.getContenido(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
}
