/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import javax.swing.JOptionPane;
import logica.ControladorVentanas;

/**
 *
 * @author Gabriel
 */
public class vistaJuego extends javax.swing.JFrame {
    ControladorVentanas controlador;
    /**
     * Creates new form vistaSesion
     */
    public vistaJuego(ControladorVentanas controlador) {
        this.controlador=controlador;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPartida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();
        btrnCrearJuego = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();

        textPartida.setBackground(new java.awt.Color(240, 202, 148));
        textPartida.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        btnVolverInicio.setText("jButton1");
        btnVolverInicio.setBorderPainted(false);
        btnVolverInicio.setContentAreaFilled(false);
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 90));

        btrnCrearJuego.setText("jButton2");
        btrnCrearJuego.setBorderPainted(false);
        btrnCrearJuego.setContentAreaFilled(false);
        btrnCrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrnCrearJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btrnCrearJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 70));

        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 330, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrnCrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrnCrearJuegoActionPerformed
        controlador.cambiaraVentanaRegistro2(this);
    }//GEN-LAST:event_btrnCrearJuegoActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        vistaInicio inicio = new vistaInicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        controlador.cambiaraVentanaRegistro(this);
      
    }//GEN-LAST:event_btnRegistrarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JButton btrnCrearJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textPartida;
    // End of variables declaration//GEN-END:variables
}
