/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

/**
 *
 * @author Gabriel
 */
public class vistaInstru2 extends javax.swing.JFrame {

    /**
     * Creates new form vistaIntru2
     */
    public vistaInstru2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInstru1 = new javax.swing.JButton();
        btnInstru3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instru2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnInstru1.setText("jButton1");
        btnInstru1.setBorderPainted(false);
        btnInstru1.setContentAreaFilled(false);
        btnInstru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstru1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 140, 70));

        btnInstru3.setText("jButton2");
        btnInstru3.setBorderPainted(false);
        btnInstru3.setContentAreaFilled(false);
        btnInstru3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstru3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstru3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 130, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstru1ActionPerformed
        vistaInstru1 instru = new vistaInstru1();
        instru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInstru1ActionPerformed

    private void btnInstru3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstru3ActionPerformed
        vistaInstru3 instru = new vistaInstru3();
        instru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInstru3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstru1;
    private javax.swing.JButton btnInstru3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
