/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class vistaJuego extends javax.swing.JFrame {

    /**
     * Creates new form vistaSesion
     */
    public vistaJuego() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPartida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();
        btrnCrearJuego = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textPartida.setBackground(new java.awt.Color(240, 202, 148));
        textPartida.setBorder(null);
        getContentPane().add(textPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 638));

        btnVolverInicio.setText("jButton1");
        btnVolverInicio.setBorderPainted(false);
        btnVolverInicio.setContentAreaFilled(false);
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 180, 90));

        btrnCrearJuego.setText("jButton2");
        btrnCrearJuego.setBorderPainted(false);
        btrnCrearJuego.setContentAreaFilled(false);
        btrnCrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrnCrearJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btrnCrearJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 420, 100));

        btnUnirse.setText("jButton3");
        btnUnirse.setBorderPainted(false);
        btnUnirse.setContentAreaFilled(false);
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 430, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrnCrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrnCrearJuegoActionPerformed
        vistaCrearJuego CrearJuego = new vistaCrearJuego();
        CrearJuego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btrnCrearJuegoActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        vistaInicio inicio = new vistaInicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        if (!textPartida.getText().isEmpty()) {
            vistaLobby lobby = new vistaLobby();
            lobby.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Poner Datos Correctos", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnUnirseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnirse;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JButton btrnCrearJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textPartida;
    // End of variables declaration//GEN-END:variables
}
