/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

/**
 *
 * @author Gabriel
 */
public class vistaInstru1 extends javax.swing.JFrame {

    /**
     * Creates new form vistaInstru1
     */
    public vistaInstru1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnInstru2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instru1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnInicio.setText("jButton1");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 160, 100));

        btnInstru2.setText("jButton2");
        btnInstru2.setBorderPainted(false);
        btnInstru2.setContentAreaFilled(false);
        btnInstru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstru2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstru2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 170, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstru2ActionPerformed
        vistaInstru2 instru = new vistaInstru2();
        instru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInstru2ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        vistaInicio inicio = new vistaInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInstru2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
