/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebaservidor;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author USER
 */
public class FrmLobby extends javax.swing.JFrame implements Observer{
    Thread hiloCliente;

    /**
     * Creates new form Lobby
     */
    public FrmLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosConectados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lobby");

        usuariosConectados.setColumns(20);
        usuariosConectados.setRows(5);
        jScrollPane1.setViewportView(usuariosConectados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea usuariosConectados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Mensaje mensaje=(Mensaje) arg;
        if(mensaje.getTipo().equalsIgnoreCase("Usuarios")){
            String[] nombresDeUsuario=conseguirNombreDeUsuario((String)mensaje.getContenido());
            for(String s:nombresDeUsuario){
                
                String mensajeActual = usuariosConectados.getText();
                usuariosConectados.setText(mensajeActual+"\n" + (String) mensaje.getContenido() + " se ha conectado!!!!\n");
            }
        }else if(mensaje.getTipo().equalsIgnoreCase("Usuario agregado")){
            String mensajeActual = usuariosConectados.getText();
            usuariosConectados.setText(mensajeActual+"\n" + (String) mensaje.getContenido() + " se ha conectado!!!!\n");
            System.out.println((String) mensaje.getContenido());
        }
    }
    
    public String[] conseguirNombreDeUsuario(String texto) {
        return texto.trim().split("\\s+");
    }
}
